-- Migration 065
-- Fondamenta server-only del primo agente KONA AI: Guardian.
--
-- Gli operatori segnalano problemi attraverso una Netlify Function autenticata.
-- Mirko conversa con il Guardian tramite un bot Telegram privato. Il browser e
-- Telegram non accedono mai direttamente a queste tabelle: tutte le operazioni
-- passano da backend con service role e controlli espliciti di identita'.

BEGIN;

CREATE TABLE IF NOT EXISTS public.kona_ai_incidenti (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  numero bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  stato text NOT NULL DEFAULT 'raccolta' CHECK (
    stato IN (
      'raccolta',
      'ricevuto',
      'in_analisi',
      'in_attesa_approvazione',
      'fix_approvato',
      'in_lavorazione',
      'in_test',
      'risolto',
      'archiviato'
    )
  ),
  priorita text NOT NULL DEFAULT 'media' CHECK (
    priorita IN ('bassa', 'media', 'alta', 'critica')
  ),
  sorgente text NOT NULL DEFAULT 'crm' CHECK (
    sorgente IN ('crm', 'telegram', 'monitoraggio', 'sentry', 'manuale')
  ),
  titolo text,
  descrizione_iniziale text NOT NULL,
  riepilogo_ai text,
  riepilogo_risoluzione text,
  reporter_id uuid REFERENCES public.profili(id) ON DELETE SET NULL,
  reporter_nome text NOT NULL,
  pagina_path text,
  pagina_titolo text,
  user_agent text,
  contesto_client jsonb NOT NULL DEFAULT '{}'::jsonb,
  telegram_chat_id text,
  telegram_message_id bigint,
  notificato_telegram_at timestamptz,
  dettagli_tecnici_scadono_at timestamptz NOT NULL DEFAULT (now() + interval '90 days'),
  ricevuto_at timestamptz,
  risolto_at timestamptz,
  archiviato_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT kona_ai_incidenti_titolo_length CHECK (
    titolo IS NULL OR char_length(titolo) BETWEEN 3 AND 180
  ),
  CONSTRAINT kona_ai_incidenti_descrizione_length CHECK (
    char_length(descrizione_iniziale) BETWEEN 3 AND 4000
  )
);

CREATE TABLE IF NOT EXISTS public.kona_ai_messaggi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incidente_id uuid NOT NULL REFERENCES public.kona_ai_incidenti(id) ON DELETE CASCADE,
  canale text NOT NULL CHECK (
    canale IN ('crm', 'telegram', 'guardian', 'codex', 'sistema')
  ),
  autore_tipo text NOT NULL CHECK (
    autore_tipo IN ('operatore', 'mirko', 'guardian', 'codex', 'sistema')
  ),
  autore_profile_id uuid REFERENCES public.profili(id) ON DELETE SET NULL,
  testo text NOT NULL CHECK (char_length(testo) BETWEEN 1 AND 8000),
  metadati jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.kona_ai_approvazioni (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  incidente_id uuid NOT NULL REFERENCES public.kona_ai_incidenti(id) ON DELETE CASCADE,
  azione text NOT NULL CHECK (
    azione IN ('analizza_guardian', 'analizza_codex', 'prepara_fix', 'test_staging', 'rilascia_produzione', 'archivia')
  ),
  stato text NOT NULL DEFAULT 'in_attesa' CHECK (
    stato IN ('in_attesa', 'approvata', 'rifiutata', 'eseguita', 'scaduta', 'fallita')
  ),
  richiesta_da text NOT NULL DEFAULT 'guardian',
  richiesta_messaggio_id bigint REFERENCES public.kona_ai_messaggi(id) ON DELETE SET NULL,
  decisa_da_profile_id uuid REFERENCES public.profili(id) ON DELETE SET NULL,
  decisa_da_telegram_chat_id text,
  motivazione text,
  risultato jsonb NOT NULL DEFAULT '{}'::jsonb,
  scade_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
  decisa_at timestamptz,
  eseguita_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.kona_ai_telegram_sessioni (
  chat_id text PRIMARY KEY,
  incidente_attivo_id uuid REFERENCES public.kona_ai_incidenti(id) ON DELETE SET NULL,
  ultimo_update_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.kona_ai_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_kona_ai_incidenti_updated_at ON public.kona_ai_incidenti;
CREATE TRIGGER trg_kona_ai_incidenti_updated_at
BEFORE UPDATE ON public.kona_ai_incidenti
FOR EACH ROW EXECUTE FUNCTION public.kona_ai_touch_updated_at();

DROP TRIGGER IF EXISTS trg_kona_ai_approvazioni_updated_at ON public.kona_ai_approvazioni;
CREATE TRIGGER trg_kona_ai_approvazioni_updated_at
BEFORE UPDATE ON public.kona_ai_approvazioni
FOR EACH ROW EXECUTE FUNCTION public.kona_ai_touch_updated_at();

DROP TRIGGER IF EXISTS trg_kona_ai_telegram_sessioni_updated_at ON public.kona_ai_telegram_sessioni;
CREATE TRIGGER trg_kona_ai_telegram_sessioni_updated_at
BEFORE UPDATE ON public.kona_ai_telegram_sessioni
FOR EACH ROW EXECUTE FUNCTION public.kona_ai_touch_updated_at();

CREATE INDEX IF NOT EXISTS idx_kona_ai_incidenti_stato_updated
  ON public.kona_ai_incidenti(stato, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_kona_ai_incidenti_reporter_created
  ON public.kona_ai_incidenti(reporter_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kona_ai_incidenti_priorita_created
  ON public.kona_ai_incidenti(priorita, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kona_ai_messaggi_incidente_created
  ON public.kona_ai_messaggi(incidente_id, created_at);
CREATE INDEX IF NOT EXISTS idx_kona_ai_approvazioni_pending
  ON public.kona_ai_approvazioni(incidente_id, created_at DESC)
  WHERE stato = 'in_attesa';

ALTER TABLE public.kona_ai_incidenti ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kona_ai_messaggi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kona_ai_approvazioni ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kona_ai_telegram_sessioni ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.kona_ai_incidenti FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.kona_ai_messaggi FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.kona_ai_approvazioni FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.kona_ai_telegram_sessioni FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.kona_ai_incidenti_numero_seq FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.kona_ai_messaggi_id_seq FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.kona_ai_touch_updated_at() FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE public.kona_ai_incidenti TO service_role;
GRANT ALL ON TABLE public.kona_ai_messaggi TO service_role;
GRANT ALL ON TABLE public.kona_ai_approvazioni TO service_role;
GRANT ALL ON TABLE public.kona_ai_telegram_sessioni TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.kona_ai_incidenti_numero_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.kona_ai_messaggi_id_seq TO service_role;
GRANT EXECUTE ON FUNCTION public.kona_ai_touch_updated_at() TO service_role;

COMMENT ON TABLE public.kona_ai_incidenti IS
  'Incidenti tecnici KONA AI Guardian. Accesso esclusivamente server-side.';
COMMENT ON TABLE public.kona_ai_messaggi IS
  'Cronologia conversazioni CRM, Telegram, Guardian e Codex per incidente.';
COMMENT ON TABLE public.kona_ai_approvazioni IS
  'Registro delle azioni sensibili proposte dal Guardian e approvate solo da Mirko.';
COMMENT ON COLUMN public.kona_ai_incidenti.dettagli_tecnici_scadono_at IS
  'Data obiettivo per eliminare contesto tecnico dettagliato; il riepilogo incidente resta permanente.';

COMMIT;
